version: '2'
services:
  web:
    image: deepqa:latest
    ports:
      - "8000:8000"
    volumes:
      - ~/deepqa/logs:/root/DeepQA/logs
      - ~/deepqa/model:/root/DeepQA/model
      - ~/deepqa/model:/root/DeepQA/model-server
    depends_on:
      - redis
  redis:
    image: redis